---
# Source: hello-world-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-operator-hello-operator-serviceaccount
  labels:
    helm.sh/chart: hello-world-operator-0.0.0-dev
    app.kubernetes.io/name: hello-operator
    app.kubernetes.io/instance: hello-world-operator
    app.kubernetes.io/version: "0.0.0-dev"
    app.kubernetes.io/managed-by: Helm
