apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: hello-world-operator
    app.kubernetes.io/name: hello-world-operator
    app.kubernetes.io/version: 24.7.0
    stackable.tech/vendor: Stackable
  name: hello-world-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
